name: test

on: [push, pull_request]

jobs:
  test:
    name: PHP-${{ matrix.php }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        php: [7.4, "8.0", "8.1"]
    env:
      PHP_VERSION: ${{ matrix.php }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: pecl
          extensions: >
            curl, openssl, mbstring, zip
      - name: Check Version
        run: |
          php -v
          php -m
          composer -V
      - name: Prepare
        run: |
          composer update
      - name: Test
        run: |
          composer test
